on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/checkout@v2
      - name: Launch Scala Steward
        uses: NomadBlacky/scala-steward-action@cdd2649f4c798c26adac85475f5392e6e83980b4
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repos-file: repos.md
          author-name: bot-nomadblacky
          author-email: 73433039+bot-nomadblacky@users.noreply.github.com
